### ISSUE TITLE
关于 YouTube 策略组

### ISSUE THREAD

**Issue by HotKids** [Fndroid/specialReg#1]
Fndroid 您好，现有 YouTube 策略组在进行正则替换时漏掉如下规则：
DOMAIN-SUFFIX,youtu.be,Proxy,force-remote-dns

**Comment by Fndroid** [comment]
这个域名是Youtube的短网址，是用来重定向的哦

**Comment by chochosan** [comment]
嗯 会造成策略组在 Surfboard 上无法生效

**Comment by HotKids** [comment]
好的，多谢。已找到原因：
少了这条规则
DOMAIN-KEYWORD,youtube,Proxy,force-remote-dns
已麻烦 LHIE1 在规则中重新加入此条，F 大能否考虑将此条规则加入正则替换？

**Comment by Fndroid** [comment]
加上了，你再试试

**Comment by HotKids** [comment]
再次感谢，可以正常使用了。

**Comment by HotKids** [comment]
您好，YouTube 还需要加上这条DOMAIN,youtubei.googleapis.com,Proxy,force-remote-dns
